version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-clinica
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_NAME=your_database
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

  db:
    image: postgres:13
    container_name: backend-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
